version: '3.8'

services:
  # Single container running everything
  app:
    container_name: multi-site-app
    build:
      context: .
      dockerfile: Dockerfile.multi-tenant
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"  # Backend API (optional, for debugging)
    volumes:
      # Persistent data
      - mongo-data:/data/db
      - uploads:/app/uploads
      - ./logs:/var/log/supervisor
      
      # Configuration files (for updates without rebuild)
      - ./sites-config.json:/app/sites-config.json:ro
      
      # SSL certificates (if using HTTPS)
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://127.0.0.1:27017
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - CORS_ORIGIN=*  # Allow all origins in multi-tenant setup
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongo-data:
    driver: local
  uploads:
    driver: local