version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4321:4321"
    environment:
      - PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/codersblog?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
      - UPLOAD_DIR=/uploads
      - CORS_ORIGIN=http://localhost:4321
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/uploads

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=codersblog
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data: